# Generated by Django 4.1.1 on 2022-10-06 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='c_accholdername',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='c_accnumber',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='c_ifsc',
        ),
    ]
