# Generated by Django 4.1.1 on 2022-10-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_seller_s_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='c_name',
            new_name='c_secondname',
        ),
        migrations.AddField(
            model_name='customer',
            name='c_firstname',
            field=models.CharField(default='', max_length=20),
        ),
    ]
